# SOPS-encrypted. credentials.json from `cloudflared tunnel create drop`,
# tunnel 594babd5-4f2f-48f4-b35a-a8839a1af835.
#
# The gaben.y4bo.com CNAME lives in Cloudflare, not in this repo.
apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: drop
type: Opaque
stringData:
    credentials.json: ENC[AES256_GCM,data:VzX36gH23V8GiSLuP1JH54QJScQa8iTHm6fAOX1N1eHPCeuNKjoPiDvFeodyfVz2kkYDKeaFwEB9R77QTjgge6ryuBpU6qdO0OE2ZzJ7U8BXVTuXDwTqK5Fd3MlLP1uCi0i1rUp1rf6LdEYYN6z99T3SBKGj/9y/CNMTsV4m+FooA+ppdN/ZJjVXVy3oQ6xHTAM+cW8a6/5uUjp91dFJLf9SKNklN0VXBNx/UugAsuA=,iv:7e+VdJ/5qHjodGCbVsAYqWONgjWHYCk39DBpWTolxuo=,tag:zCvKkD4Sc4TCkdr7dA6tlQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM3l6amxvbU5NV25RWUlU
            ajQ1cjRqVXEvUC9UWVBzWTdOSjJrSm9SbHpZCmdISFBpdnBoMWNhY1BvYUlYK2M5
            T2lPTmJ2S3dJWUdMNHowQnFqcGtYYTAKLS0tIHZCUXZsaUNUdGExOEhORDREekEw
            dSs3dm9RT2NoYndVZzQ3UldYVHVEMmsKqaK8Hi5pPDduO+HiL8takT0cD0fdzm8R
            WZfJvNwQtmoxxqszvnquKGpnEqre6dS+cs2NgLWj0GXGNlskiYoWlQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T04:29:45Z"
    mac: ENC[AES256_GCM,data:ZrTmwsc4ftrHYAhfBhlyM2aZlf65VWI40qNlLjBZdE7rrJ8IIwTHUIHL9d/F7yFZNQ0f5fQIBzBt3zi7KSKC0bp1BPXti/UAid4ehoTshDGWX/ldSbvUpsyFEiTZl5Ze5Bg14reuvoKd+B3j51AllHy4qBmwJEhkNK8XJbuv5eM=,iv:kl5fJR9/4Bam5vTVxLC3Fc/EU4lFrh38FoIqlZ96BoQ=,tag:xSf+N8NjDD03qqR0jae/Sg==,type:str]
    version: 3.13.3
