apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:iRPlKzgLyBCHKUmvbD8ZzJHOUmmx2nDbecjRIuMJpasPWBVv4s5w53LcXW42iC2Bh8FTyxDslWWgB2VLvEMCyqyX3lKqFJMCfexh+279F9Q/cwsCzXxgo71DivKiUCrOOAfiJd4m+dNt7/9GHY11YY33W4psHPsPBgirOD4y86N0HU5rqfS1gRyqNW12eDLiTY1WstCmny5zR3cxww6ysie7tgLsrMgANSdMoNSWeTYjtlun2OVdGaU7ukkg1l40TYqhOLSy6KYDnLOTtI+ZZaZumOMIHP2Lfbyg9SlWGEcDoOcY8K8NwsBiYWA=,iv:T3UNiGLr/ZluHCWACUkM9rcQ/IwBy9E19t6GWZ9OE5Y=,tag:OWX5HL2i3nDp8t8XHEJRYA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQTRiMjhPeFpGQVkybDhK
            Tzg0NHBTc1F4NHlDaUJXZEJNbzRFK29BTTJvCklyMzNIUUlPOWczbzhaKzlqeHJX
            ZEtvQVlDUFpPL2hKdzViTXFMdmQ5MWcKLS0tIHlvZXZpTDlGbWNCZGhEQjdZZHdC
            RHhWbW5Ba21CcjBlQTFHWk5YSm8wTTQKhSqFj6AFBC7iZOk2NTVGiag9ztORWufO
            RZ+rkxgBEtn5I74son4dMVPBu+tWOUvbAyJOCDGYRVoIWrdWGBzTfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T20:26:41Z"
    mac: ENC[AES256_GCM,data:z3MaWfLOhwSwrUQ+ngzYmRd6lS+rvUOAF7dExrT6OLGdUKYprSrZ+5xVkYxmoj9hMs359erGgV9kD33b60KmxbF4QA0Uptg4nqYnHP3GRCZF//KIQA3XKXJ6B+ZgL6qXkdAfA6a0/lVE+p4ZMPm3OkXlJd+JXAx4G6Ae85I0hyA=,iv:W29cbPfFJh6pdsL4x6KmWlCjXHeDKeKlBkc9fW8PyPg=,tag:2UCpeLYyNlEFnS4skBj4Qw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
