apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-pv
spec:
  capacity:
    storage: 11Ti
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/media
  persistentVolumeReclaimPolicy: Retain
