apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - storageclass.yaml
  - servicemonitor.yaml
#  - recurring-jobs.yaml
patches:
  - patch: |-
      - op: replace
        path: /metadata/annotations/storageclass.kubernetes.io~1is-default-class
        value: "false"
    target:
      kind: StorageClass
      name: local-path
