apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      # securityContext:
      #   fsGroup: 33 # www-data group ID
      #   runAsUser: 33 # www-data user ID
      #   runAsGroup: 33 # www-data group ID

      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.33.1
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: America/Los_Angeles
          volumeMounts:
            - name: audiobooks
              mountPath: /audiobooks
              subPath: audiobooks
            - name: config
              mountPath: /config
            - name: metadata
              mountPath: /metadata
      volumes:
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobookshelf-audiobooks-pvc
        - name: config
          persistentVolumeClaim:
            claimName: audiobookshelf-config-pvc
        - name: metadata
          persistentVolumeClaim:
            claimName: audiobookshelf-metadata-pvc
