apiVersion: v1
kind: Secret
metadata:
    name: lldap-admin-proxy
    namespace: lldap
stringData:
    client-secret: ENC[AES256_GCM,data:xMLEYdmFr7+TjAgzrmDIzGwE9AembAIDNoeRUpT5FW8=,iv:oPuGqC5OS2luYmfxKZLnRpM/89vBkdcQcT2DQqG/818=,tag:t/k93QwTKH6aDImVvHXfEg==,type:str]
    cookie-secret: ENC[AES256_GCM,data:7ztPc+Iq+s3bysYEmOJsMqqkjAxMrco3JHlTTJ13E87bLtwZNJx3s6MXL9o=,iv:Yt5nEUXkulvjtfGF0IRJaHp0+JLdJuF+ZF0CXjOHvpY=,tag:NU5XFrbjVEZjdz/SNG5d4w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2NUVZQ0xXSVI4blRNR1hq
            WTBJajJTdUxlWnZBeHRCRmhqbHdvT0RhUUVBCmEyd2djamZqNGZDcjlwdEhvOXlQ
            dGE3RWpXSHMraVp1bGRYY3hCZ0M1cUUKLS0tIEJueklZc05nbXpLUHZPRjhhdkc0
            ditLRGJZckxUakFMSjZSUDhVRXRjV2cKxcR9bm929DXtD49+kSIOe1BPPLR9Wnxq
            K+zS62wycd8XlAtG/NSoEr3ZJ93CkUAlPWH/PrYoSybaJngzJOn+XQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T00:21:53Z"
    mac: ENC[AES256_GCM,data:MG8r4/80pd3zaaNY/p0hRIKbpLH/gyHD2PrSTLce22e1/od8bvPzIFIvqwjXQYlxEfBh4IJKRh/AHSw/3ismU+gMhXHwE+EdT7YZFGt86prJUYtTvmjsnL/RxPb52PV8zx7jO9MwaCX2o44wy1LYzVMkFxxsM0yhiVggjpRYQAY=,iv:VuKACTjUEU9/Y7Bjfyvd9O+Sp39gouyDm2hRk1vRQW8=,tag:ov63xei6NdJh0hU5w+LtfA==,type:str]
    version: 3.13.3
