apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:qDPGsYb61VTkHXdlE5xHVQ5+1U0VNqeYfYyVPyx48PzI9rFOHdnQ8QyNMKzT/q5e6RcqNDfhaZ7bnrsfjWn2yPKKJPbCpad939oZFZYKplk0Xk8X4iwbV+OSmk1cFUCrsftWoKQGh2Mt599wicEhILgrfnKuufzyrRKx6gM2bB5rCBZLvns0Ht90MCTOlFqUjy5ljxS5xlucrxU4ggIN9KHZe8bNXDu6X1Hm6CgWRDqDJkyGCyvULdJga5Z3a+sOpqtxHKtfVVV+opLGar7eHmYhP1yXV1lfYpZzD6LsmAFYyCCmYKaVzuoh1iI=,iv:jGPA2HfTbovmhX++6R1Qj/wC1XJQ54lU9mNWP+tEjRk=,tag:QPT75RZrBNVJr0R+TS5wlA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: lldap
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQSzhLY25ESjFSQmVvZVFW
            aVdSVDZjaFQxdGxwOVQvRXAvNVN4YWdna1ZnCm5lc2hkd1RPeDRIazc3c0k4Tmlx
            amlyUi83bnE3N01oc05hejJHUFJlVW8KLS0tIDhEM0t4OW1pRUg1anB4SmVkdGpR
            U3FjRzd2cXRYN1ZLWTB0TmtDaTdVbGcKDoNlgu5L2cRfz4tsofXvvmPAwP7d6Rsr
            Q1lyEMGWEQrAB59iU0NmC1dJuHfLw78q1f2M0gYb4q3shAHo0V6YUg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-28T00:21:04Z"
    mac: ENC[AES256_GCM,data:YLRD4G2KrKlmAHF4SEL8Yy6/OPcGrNpwFVIC8wUneqjapS9nUD+QQARG2iJsxLLWlPdT1ZAtUGFiYpBr4i0a6skEEvAiozCRVmL83ixg78+rV9aKmP27rc8U+NrKtEzY1mTC8TD0qaN0clYVHEm110iV4vcl4E0irkFXl6LID4Y=,iv:SrPuQt3MLtOIsgsfcX6/m400lV6ZDH1ZmJVKV15CnEQ=,tag:TcsvQetXhOD1ST2/x4dGMQ==,type:str]
    version: 3.13.3
