apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:69+UWPa1B5m5KM28GXk+ikyVMre63kIX4AleNVBgvh3on8EeTpoRVXBrYC1AcSr5mCEbKiUfz7hwMIwbAcrbircmi3ach/yvG+Ze6FHI6rqDEAVEpjKEZ843LVA+zoosHca1aVUKhiUcj0P1KFpczR6PBM55l+RHqDAu2aRaOEbXOT9zkigP1EHUPjuVYpm//dO8gGSajYAkxjFgt1kYQdj6dgSlEazhzzE/8G7fCwPgyEhQzjeCD6Oki92AGN84x6wdIPGc/bSr3g+oT3KlwGtUqKNdWWSzp3pTqYy4qfQlDheftsSbLTV0TZI=,iv:FjXJoxs9PbjNLbWw1rf/DCAT4P3e96qJPnNk3aGtHjw=,tag:dEi3bHVsTyqeqoTCoUI9Aw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRbGw4MXE0WFRRV0IzNFVm
            bmo1T1hmTk85dHE4QnhKL3paeDNwRkF0UlJVCkNicFBJa0ZvcUE3dmthVE5xSTVj
            THp1c3puekdtTkxkQWFTVklCTk9qL2sKLS0tIGZKNFpkNTRtbWZoV2ZRQ2RDSnkw
            bjNtaE1zVkpIS2ducEdqZjFZbXpMS3MKWresvvtv7yybWhKTvnMbEVDXB29nqRn7
            KkWsf7rW7+vMeWLNW7k3G5HafYBKXlY35Xe9jYV5Gv/IIdb3WvL04Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-02T22:24:05Z"
    mac: ENC[AES256_GCM,data:dHULl43oDRVZ4f9xC4v82nC42fbLyb4usOZJUUD8Ny+ItGplEVA65gLiWXfra5jCQI7HpmB8xPTzjN41y02iu0g10pYJ+Jy+DSBbJMGR/bvSgo+Ae+AiMYCc0TKV8w0Y+pwpt6BBvD0wIA4VUiIwHty+8gzUmmvjJN25xoSznks=,iv:3k5MhyX4yCHazfYcp3A/79EatcMptIdgCNcCuZGe9fY=,tag:NpmlkCzJJ9VJL5wKko9CSQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
