apiVersion: v1
data:
  password: ENC[AES256_GCM,data:fLdwDF0UrffdDpHM,iv:9PbD9Q1d7AaeRzMHkk+oUk9/qc8mBSjRifsbLx4XZa8=,tag:E7Nr7/Vh7yGSAOoiF1hTiw==,type:str]
  user: ENC[AES256_GCM,data:O0SQDAOXI2M=,iv:4P78AOo4E6UK5ok4pwm/qmfB0iSQ+4qkTyoh6rhv8hM=,tag:1ib6XSGfTE5nIVYbbLAmYg==,type:str]
kind: Secret
metadata:
  name: test-secret
sops:
  age:
    - recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiOU1JYTNOdUEvVFNjOUl5
        a0tOYzdvZ3dId1BqUnFMVGR1Z3QzeWRRWENvCmIvdWxUVGlMcWJkN0huSjkwVFI3
        S0h1cVNsWmZyb2VuZFN1SnUrMGdPajgKLS0tIHIzbHlJTkxUcmZCVEZOY1RRemFV
        SW02UmdvU1VQWHhxa0FSSEFxRkVtb1kK9Csg76eiHnz8Ycd+KpVNovzd7OSi4rya
        zpHMfQtPxYEY7MqjH7YzA1+rNqnpChufRoLLM8GYwkiG8hGe6xtutA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-02T20:44:25Z"
  mac: ENC[AES256_GCM,data:YyvP6IgDVA8bxYwPThwklgO2lt6ijq2Z8S7twYSuhcgwPtGJ9SKn++ltgQ41Y6nOPIidwzznFbFpz/BdYh7A21X7rTu8eMlDk7gA3J9oB1RqhKYVaMrbgVSvsvbSE8WV+QQ5dEQoO4s3aLNoaoizyxYg+wtbkfIzib9RFT2QIGg=,iv:dZ9OlA5wQpxqohkhyBnzMIQxFyEnsoAPDk7ZPj27ND4=,tag:Y6UeOG+RZFxDZOGqnXDHMw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.12.2
