apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: keycloak
data:
    credentials.json: ENC[AES256_GCM,data:fQb5HMFMH+SVTG63Kpd7MBm87SrWa0ElorssD7lE2GZp0WPK8p593IFPSW3/LvgYAi39Tm+W5iErSw8Tw5yutQkFp3CqKJzexo9Ycu9E5Fazn95ZsPj6UQdA4P/YhgiB/SflzHRwyjyzvUq6P7WOTzYCUTmbZxlfOKcEOl0snB0binr1t6uo+ahIsHe8fBXZCA9hFuvH8H/Mtmn26DB5gFWZUBWid5pFcWj6XLIy5HdtYsYsrgEaTCDPWJ61mdWNxvQbz4FjYCWyotwj4XE8HSdCPZUOWOhv1tPvNodcUmZHZTPQCm+xE//vlaw=,iv:b2fhLpMeMSuG8uvUICVu9DVCOnNmMPGwhghDmwvBAfo=,tag:yUTNk0YWX2S/XCKS1pW6CA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UHczUTl5WkM5Y2ZLTXRS
            OTZDYkpSSXhzRjhrc0dKOEVRL2VQdVY5K3hBCk53UnNEcytMc3dmdU41bXZkMVpH
            U3BFSnF0YmE3RUt0bFV6bmpNc2hOT3MKLS0tIHFyWWVNU0tXZmdKNjd5b3ZpZmZn
            b0VGY1o3Yi9MVjhDM2RIdFJvWnZuRHMK6cYRlYryYWpMU5w/zVPwkho3mjp/C/SW
            0WNJGxGf3r7s5t9UcrLmDGklG7q7PkPYl5RrKJuePownlERk4bof9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0TDNzM1ZKa2RDVzZlM0d2
            cDNQNTJ1Q0tzOTcrNmVMcXBOUjhLVGc2TjFFCkdJSDhWbmZrRWlFV081VVBTME1D
            WU9ibWFyOU0vOGE1VnZlT2FkTkZBVEkKLS0tIHBKSDdzNk01TmpWUHRmU0Zzb2lQ
            ZVdPTzdkMTlLeXVJemJ5ZGg0MFpsakkKMVGhaSR+qts/3XPK6caE+/uaTWpK56JC
            RKwpOqeESqmxI9dOlzYjcf05faaQ5YcD9vDZTBXybD0WAaLuWiWg7Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T03:55:10Z"
    mac: ENC[AES256_GCM,data:XKYbkWC+jrc2jZMOHBZu4QiDhjI0uFzyS+euwaUpGJFr/i6tSpUqPFjeDbTUxQM8SHK/cleZdB4SeRvsxFtrGbdquI6UJTVYCJulR8CPmauNDpmQhWZ5UPCU2ZNSDjx00QCsHtRwxJb5rd9fLwvNHzzDAmHCb42CJL+BdCRz7k0=,iv:EJzQz52g2D/igfsqP99khp/VCKt+7jZnZxOLGVZlshI=,tag:MIHx5GdpzoWTee9R46khJw==,type:str]
    version: 3.13.3
