apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: keycloak
data:
    credentials.json: ENC[AES256_GCM,data:fQb5HMFMH+SVTG63Kpd7MBm87SrWa0ElorssD7lE2GZp0WPK8p593IFPSW3/LvgYAi39Tm+W5iErSw8Tw5yutQkFp3CqKJzexo9Ycu9E5Fazn95ZsPj6UQdA4P/YhgiB/SflzHRwyjyzvUq6P7WOTzYCUTmbZxlfOKcEOl0snB0binr1t6uo+ahIsHe8fBXZCA9hFuvH8H/Mtmn26DB5gFWZUBWid5pFcWj6XLIy5HdtYsYsrgEaTCDPWJ61mdWNxvQbz4FjYCWyotwj4XE8HSdCPZUOWOhv1tPvNodcUmZHZTPQCm+xE//vlaw=,iv:b2fhLpMeMSuG8uvUICVu9DVCOnNmMPGwhghDmwvBAfo=,tag:yUTNk0YWX2S/XCKS1pW6CA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkaW11VGxvc2I2L1NFM09K
            UmFsRU1WcU40V2JERmppNTdlQlZQR1kwUjBNCnFwMGMreHFvcFAvNTJlNS9xS1Y1
            c3MrMzFNUkVUbFM3NUZyeXdwc3NEMlkKLS0tIG91K0g5a3hiNXhMdndIQ2hna05D
            TkQ2a3QvV0xWVlIzTitCUlNtUkZDeTAKxzHFr0zQjTEt838yxsRBuqYsSLpgVIh8
            OS/z8h4T8PuKa2A10Af1YjZK7ovLIMKQnuLfADzihO5XQzZrKgMtxw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T03:55:10Z"
    mac: ENC[AES256_GCM,data:XKYbkWC+jrc2jZMOHBZu4QiDhjI0uFzyS+euwaUpGJFr/i6tSpUqPFjeDbTUxQM8SHK/cleZdB4SeRvsxFtrGbdquI6UJTVYCJulR8CPmauNDpmQhWZ5UPCU2ZNSDjx00QCsHtRwxJb5rd9fLwvNHzzDAmHCb42CJL+BdCRz7k0=,iv:EJzQz52g2D/igfsqP99khp/VCKt+7jZnZxOLGVZlshI=,tag:MIHx5GdpzoWTee9R46khJw==,type:str]
    version: 3.13.3
