apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:VxIxiyv7OmL5b/NSdHUSAT9+/Zf+d7oNWs0UPCGm80aj07DcKfuxwSl5Ow72XOlKHPA=,iv:CdVl2E5w3C4/urEQlfw6Ydr8h4RrCjgHZk8m7cwipaY=,tag:KvJaKD08dVX4tr1RCEAhug==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:yL6j4A==,iv:aPrN7D4chNjvWrO66VBLVkHJxWP8O7UcZVoUpokxJpA=,tag:Ntcic17ihGemsUoehs3zdw==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:zsBxvm7xwS2q5MFujokiE3F7e+c=,iv:KT9704COCUfy5xMUcEGSZXtOfjF4HDI9ZxSMXTUrRDQ=,tag:n7QzAkr/d7YYE9j9S4uCEQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeVNVQzhDdFJSODB2dklU
            UzFuaXJacHhCODlHK0lxNFBFcGFXSUxKZEhrCndNVkVRSTE4blMyVi95clNVSW5M
            V1hSNzNkWGFPUzVTWlJ6WWJOeGtzU1EKLS0tIHM5YnNXRGQyNVZyejlNRFFWZGF1
            b2FtWnJwTEZyUUF6cklvcWx0SEJSOUEKQhZ9crXtfsD0wbui5/jDw70mEguqgx/E
            ouyBvCjgq1oO6NGX8TZ1hSOdSWBKz0tp8viTer/F/Jc6RyR4BCbB6w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T04:49:43Z"
    mac: ENC[AES256_GCM,data:bE4OR9xaSBuOOm25vR8qFlRxbfCvI6GzgsQHdTYI8Yi+kuJrDkD7/t+Eo2QgdMa6OOPMzMouUI064FeW3pXr3i5QvvPS9tljEx6U0qqmZrK7ljA+Ud/p3oLveNfmvOeUEhnewUqCI09uW9BmrLagAFTuGrjaZjJEyae0xlv2U9M=,iv:pUNcO4ZmEpdazv9JnBZbPmBfig9mEOVZcjZZzN3PWoM=,tag:3ENWo9F1pqePO3kPv5K6fQ==,type:str]
    version: 3.13.3
