apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: portal
data:
    credentials.json: ENC[AES256_GCM,data:8l6rINcvs0/lr28YG5HrFs3KZS7wy2w5OgxcGJEi/sh7Xwo6TwEY2F+AgbyWTNc8iRgMM9mCJX1R+37u2NpqtQfZvyWbfrreBc/zVAVxKEEKj1AdGO4S2tdHMnST/kG45yXtPvztDMFscGfn+x6xaDSM1H7UXVN1b/C17JtDmx9wPIFGl5HuTdimszDdiWtifz+QQZjbr+IYmcR1x5MT9s/VnUEWzHhvOdTYZV4BtT987DNnYI70/GutCX0Nk+vhwLxFEwr8OWIW8yhiG5sMHVPpqA+/pLl7IS9kdE2AXUe8G7nOlBtcLefOIz8=,iv:/JW8Pc45MOJyb16KqWGLsUuMpeUAgWC6wpcZGsySQwU=,tag:sAxi8biGsVJYg3sn5JDaNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Skk2V1JRdG8rQ29sNHha
            ZWt3UHMvNFErdTF2R245d2RRdTBKdFBKYWdjCmZoSkpldktraG40SnFwWVgwVWNY
            NTVTcXJvdER1Z1JiZzhOMGl2Sm9RRVEKLS0tIEoxMkhrSmw1dlcvb1ZGS1JqZGx0
            MlhmMlVZcmRaQ2tvTjZCZTZwcWdEN2sK2czqfG7s2/ZItcmphoYxVsytkXqc3qJI
            LvzoqLYjwDFEPEacMjMOODlu3dtnaa/+jpCzMjD3T+vs6nXlt1sZvA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4NktFam1vWU5JK3VmaHFn
            dy94RGRlQzExRlVOZk9MUnF3SUhBQ0VSV0NNCjhwTGY5K0ptMEZHUll6dWFQY0xV
            M3l5TGJqb1NsZmZtZW8yNVpQeW9QZ1kKLS0tIHJHSllobE1vdVRrN1RIWWRPaktx
            SUpPdnVXSkg5bjAzU0ZITGF3WmRRQ1kK+avN16FH/XK7S/mu8g/qlZya5/yQueYt
            l1fwBVECNPUQXyxbBZZOF5huHSR/xGR635nw7ON5uo1OyR6OUm2poA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T03:55:09Z"
    mac: ENC[AES256_GCM,data:X8Vb7Ke19z64SIpyRYPi9lc2Ofif85o1Sxj9i2m0u6l7OxcGxpaya+MyDnkG8wKbF0UgSE9PPqiKixqvgVyBhZoo/TwZKEbnUFEw+VGohot2KmLDSYrAcTVPQllUTdmacbGqpo+v8w9LmFXA5RQUCaHZkCoFjUqWTo/L2N8yQq4=,iv:IQ2xC85GkUNxJ6+8rxGXL+sbX2+/MtLUDeovx2TPV6c=,tag:YiDqn5II6reMLZnsUqj2Qw==,type:str]
    version: 3.13.3
