apiVersion: v1
data:
    GF_SMTP_PASSWORD: ENC[AES256_GCM,data:p7qJAsPjvCYk0puGL/xuPYeGNL4DAval,iv:izxALW4t2rvnjPL8ysr6GEOn+Rym1r6fx+vkAn+xMM8=,tag:xZntg/lE/nFBm0CqP6nRvg==,type:str]
    GF_SMTP_USER: ENC[AES256_GCM,data:jWidgEM0DA1xGaOn+PUDnJOzG1Y=,iv:HyDWZzDpSO3wu1/goFUf+1+GE09ZqFnNrvIz3xuILhE=,tag:vTLMAqsfmbYe0PCEbnDH7g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-smtp
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN0IxU1Q5eE95Tms2aU5h
            cFdwUC9HeEprTWFRakt4dnpIT2l1REFPSkZBClVLSnJrYjhWQ1J5Y1dDeFozNDlX
            R3drWjN1WmJlc0hGSFQwM0pyVXVkNzgKLS0tIFJud1FyYjhxeW5OWUwrY3AreG4y
            MHFGU0pDVy9TS3BjaW4zY2Vuc3VBbzQKeTgIuQaikf7cZg70DcelXbaG3k4oJxLY
            z1Ci9KyarjGf+fmBoYGChY7fy3+K7X7bNZVQpsrVvQSwwz1zb2D6jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxaW02MnBpSUdJa1gyanhz
            a1FxeHpzNzh3ZmFQdEpheGZ2VUtKWUZtV2lrCjRPZW50enBYTUk0WG10cGZKbWZx
            NmlGOE1xZ2JYazZqUGtnQkdBSGN5Sk0KLS0tIHljTWhrS1l4dnpFK3ErallwZWh4
            eUtjR1ZocnZrTC9VQ2RFb3R2ejdFZ00KNQL7hUnMWujBH8ibwL8wiLQaT1ZNU3lP
            e2HUxYCjBX29gisCdV9rS8sZuZNy272MYG/7yFIN62hLt25AWvuygg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T18:16:50Z"
    mac: ENC[AES256_GCM,data:xZE5PEEl7wcXZJNEXP9Hs/+Nqnc+cGlp2s0vlY8sl84KdBTUdExmHqI2lwhPtk85vwphjLSnzTu4UImhEOd8B2lEA0kTqMML/CAIscpOTMzGLXj2E8ZCsuwLPMgdvSJt49YJA0DyCeYqj1qfE2JTdLX7zHZe83p4ZxuiSPkOSR4=,iv:aoUIMXDa5pSMEbuUqT558g67wkIUgXcRRXV+w6xgJcQ=,tag:zGPRmeEojtMz8IPQJvR4Aw==,type:str]
    version: 3.13.3
