apiVersion: v1
data:
    GF_SMTP_PASSWORD: ENC[AES256_GCM,data:p7qJAsPjvCYk0puGL/xuPYeGNL4DAval,iv:izxALW4t2rvnjPL8ysr6GEOn+Rym1r6fx+vkAn+xMM8=,tag:xZntg/lE/nFBm0CqP6nRvg==,type:str]
    GF_SMTP_USER: ENC[AES256_GCM,data:jWidgEM0DA1xGaOn+PUDnJOzG1Y=,iv:HyDWZzDpSO3wu1/goFUf+1+GE09ZqFnNrvIz3xuILhE=,tag:vTLMAqsfmbYe0PCEbnDH7g==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: grafana-smtp
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpV0ZpeFRSZ0R4UnRjRGRp
            M285c2JNK0Z3YXkvOEY3b2krZXh6cWZ1UkNrCm5MMnVLcUJYMk1UOU1YZ0Q2OS9D
            Z2h1SlZoYTZLUmM3dmhxKzE4Q1NTSFkKLS0tIFFGM0IwNkhMaTRYL2xpT2lobGJa
            OU12d0tITnVRNi82SC9pV3VHN1h5VEUKj0c5B77CNgq/CA3SiwKb7NISFfyYbnxL
            DEmOgdOoqgrNWiKsGF33k/BYHTcZTIABP9poyzVxjwAPquKQpNXqdg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T18:16:50Z"
    mac: ENC[AES256_GCM,data:xZE5PEEl7wcXZJNEXP9Hs/+Nqnc+cGlp2s0vlY8sl84KdBTUdExmHqI2lwhPtk85vwphjLSnzTu4UImhEOd8B2lEA0kTqMML/CAIscpOTMzGLXj2E8ZCsuwLPMgdvSJt49YJA0DyCeYqj1qfE2JTdLX7zHZe83p4ZxuiSPkOSR4=,iv:aoUIMXDa5pSMEbuUqT558g67wkIUgXcRRXV+w6xgJcQ=,tag:zGPRmeEojtMz8IPQJvR4Aw==,type:str]
    version: 3.13.3
