apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: monitoring
data:
    credentials.json: ENC[AES256_GCM,data:eL6uxOiXf6ijTXywT91bKe0GCzJWnAWh2bNVPz9vlYHucz2b+A0XQKELjk88G3p9vw+UbuThdWjVzyJ0DrKM4+Heo9OliZqZGVqMsZlOf/KfptyYAzCmT/jdYdYPNOXiPiMQ/viDiFNk0FyShLmtGATjTZd2Ruf4gJPh+9/NMywfFAXNgjhkAAeTvxrDf0jrC7eoQTJAwh1kyTEVrFOv9dwUpWyZc72CiyQpXqRQ287TXY1NNuEdGReoWqqeNrvjAZ0dbtf8ZD1ljKnOU1Fl7decVJpBW0bV9GqEjopt9qFQlMVZThEu5chKaWI=,iv:Jg+1fdSqp6FtzE8Mg2cWLUNQadhFzO876tMwacMcCEo=,tag:1FgLIbn7DYSlmZZqdpgPWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrRHZLSVNXTHV2clJsQm9l
            UWtrVkYzSFdzT1RSM3VveE0rRzN0QXJ3aVc0Ckd0a2dkcHZZUjMrS0VCMkV1M2VN
            bmhtUGlXUFd6ZnR6QWcycHdZbS9jMUUKLS0tIFVKcGNyVVpoTWROMVh2ck4zRWpL
            MUIzNFRuQnB0UVZIWVF0dndhREYzeDgKYDyumD8EgP/NCluxgRXVDpriYW8EgteM
            ZvKqB4gmvzChC9mMK/HlzHrDma763ZD/LEIFReS1kY4q5dwPBvwJXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T03:55:09Z"
    mac: ENC[AES256_GCM,data:yiGYR5GUwNuYS2o+EPdomH1ImjoVK8LS6okQdgMgxzO8tW/TY3BIqV3N3FsVCDrqh0ZyH6Qiq/QMqOpefZglIVkWXmJ8jknYYCTfwU7ctKucqMPCS5hiPkIPxf5xUnW9cyDsz6yA2I8mptYCTuNF8p3R5eZJNy0Vfa7RJVjRq+4=,iv:qrc93fn78wOafP93nO3SnUJWdMjvaFUI+GvyAK7dL20=,tag:CaQHbqUIPt824ypF+7ysjg==,type:str]
    version: 3.13.3
