apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: monitoring
data:
    credentials.json: ENC[AES256_GCM,data:eL6uxOiXf6ijTXywT91bKe0GCzJWnAWh2bNVPz9vlYHucz2b+A0XQKELjk88G3p9vw+UbuThdWjVzyJ0DrKM4+Heo9OliZqZGVqMsZlOf/KfptyYAzCmT/jdYdYPNOXiPiMQ/viDiFNk0FyShLmtGATjTZd2Ruf4gJPh+9/NMywfFAXNgjhkAAeTvxrDf0jrC7eoQTJAwh1kyTEVrFOv9dwUpWyZc72CiyQpXqRQ287TXY1NNuEdGReoWqqeNrvjAZ0dbtf8ZD1ljKnOU1Fl7decVJpBW0bV9GqEjopt9qFQlMVZThEu5chKaWI=,iv:Jg+1fdSqp6FtzE8Mg2cWLUNQadhFzO876tMwacMcCEo=,tag:1FgLIbn7DYSlmZZqdpgPWQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraUtZQkhuaXgvblpWdFVj
            aHkwSFFqRkxPOWhPdHJvY1JjWDdpWlA1aGxVCklPSWVPUWQ1Wml3dlIybEtxQUNK
            SjByWFBtbllLSStlL2E3N3NUaFIrQ3cKLS0tIGdxRi8zbkk4ZklXd1FGRyt6QnUw
            U1ZYakNZOE9hK2xsUXpUQUFab1RVZm8K09++y2/liZhlO2+2WkCbuYTLiaBycSIy
            tJZOLfTvUZgy4ToeKXMkpVyL4cAOYT1WMzjdhQfv4AwboYkdtX+3yw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zd5n9zx0dsdwdggjuvz32ppngn45gk0tcnwlwfs53ev7szefmdfqarudsl
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SDBJb2ZuWUxLTTFlWndX
            MXRHT1V0ZmJLbEJDWHVGVWhrbzlZdXREYkI0CllMTDkzM3JDUVltOUpRUzUvcFMy
            NXFHNTFVRjdsNStCUVRia1JXcUM2QkEKLS0tIHdYc3l0TmhiNTJ3NGllMTkzdSs3
            VmNTbS9wTjBCZjFNNFRzK2pPYXZSQlEKo1k2XD4U8cE9K4yiUE+8G4yxPuTITZMw
            AV54l6ylnM9uRnr5PrZE4YRZuyoAgxGEBwLu9x/jJYfWEfHH6rVWsQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1a34pfsyga0gajdy85cqy6yv6ypyumyulwshgkgm9h69jhp25dqaq4gp87a
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T03:55:09Z"
    mac: ENC[AES256_GCM,data:yiGYR5GUwNuYS2o+EPdomH1ImjoVK8LS6okQdgMgxzO8tW/TY3BIqV3N3FsVCDrqh0ZyH6Qiq/QMqOpefZglIVkWXmJ8jknYYCTfwU7ctKucqMPCS5hiPkIPxf5xUnW9cyDsz6yA2I8mptYCTuNF8p3R5eZJNy0Vfa7RJVjRq+4=,iv:qrc93fn78wOafP93nO3SnUJWdMjvaFUI+GvyAK7dL20=,tag:CaQHbqUIPt824ypF+7ysjg==,type:str]
    version: 3.13.3
